### ISSUE TITLE
Just Few UI Upgrades.

### ISSUE THREAD

**Issue by wasibiit** [saleyn/phx-multi-select#1]
Hey!! i found your select recently, its really great you have done it. 
i found current ui too crowded and compact. These are few suggestions. 

- Maybe create few variants and switch between them with some parameters on demand? 
- i'm attaching few modification suggestions, maybe y'll look into it. 
- i will try to contribute a variant that i will make out of this one. 

![image](https://user-images.githubusercontent.com/48654021/215583658-6a01589e-604b-4874-9b2c-f15129bb5b85.png)
![image](https://user-images.gi
<img width="335" alt="Screenshot 2023-01-30 at 12 08 30 PM" src="https://user-images.githubusercontent.com/48654021/215584165-2d26a121-b143-42c1-8434-b772e3c871e3.png">
thubusercontent.com/48654021/215583794-b2856e72-8102-45bf-9751-b2e5b9a28ce2.png)
![image](https://user-images.githubusercontent.com/48654021/215584414-4c7df5bc-9cda-458f-865d-20516a1c3889.png)
![image](https://user-images.githubusercontent.com/48654021/215584720-ee4bc8cd-23ac-41da-aab6-69a0c6de258e.png)
![image](https://user-images.githubusercontent.com/48654021/215584747-fd4c4f54-7294-4560-bde3-79be32a1f5d5.png)

**Comment by saleyn** [comment]
Such customization makes sense and PRs are welcome.
