### ISSUE TITLE
Docs: Use vs Import in html_helpers during installation

### ISSUE THREAD

**Issue by njwest** [saleyn/phx-multi-select#10]
Great component, many thanks for sharing this in an easy-to-use package!

Using `phoenix_live_view >=  0.20`, `use Phoenix.LiveView.Components.MultiSelect` does not work in `html_helpers` as directed by the installation instructions in this repo's `README`, only `import` works.

e.g.:

```elixir
  defp html_helpers do
    quote do
      # HTML escaping functionality
      import Phoenix.HTML
      # Core UI components
      import MyAppWeb.CoreComponents

      import Phoenix.LiveView.Components.MultiSelect
    end
  end
```

**Comment by saleyn** [comment]
I updated to latest dependency versions, but unable to reproduce your issue.  Could you provide a sample project or how you try to build?

**Comment by DougHall** [comment]
I concur with @njwest. His solution fixed an unable to find multi_select/1 error.

**Comment by saleyn** [comment]
Could you check if you can reproduce this problem in the master branch that uses `phoenix_live_view = 0.20.12`?  It works fine for me.

**Comment by DougHall** [comment]
I’m using liveview 0.20.12, Elixir 1.16.1-otp-26 and erlang 26.2.2. I have to use import. Otherwise, I get:

error: undefined function multi_select/1

Thanks,
Doug

**Comment by saleyn** [comment]
Updated.
