### ISSUE TITLE
compatibility with phoenix_html 4.0 

### ISSUE THREAD

**Issue by matthijsFoF** [saleyn/phx-multi-select#13]
Hi,

Im getting "Because every version of phoenix_multi_select depends on phoenix_html ~> 3.0 and your app depends on phoenix_html ~> 4.0, no version of phoenix_multi_select is allowed." when installing the dependencies. 

Is this component compatible with phoenix_html 4.0, or are you planning to upgrade the deps soon?

**Comment by saleyn** [comment]
Are you using the latest code in the master branch?  If you check the `mix.exs`, it shows that phoenix_html is version `4.1`, so the message you are referring to likely indicates you are using a stale version of the library.

**Comment by mckethanor** [comment]
It's the version in Hex that seems to be stale.  In a brand new Phoenix app, adding this to mix.esx:
`{:phoenix_multi_select, "~> 0.1"},`

Yields this:
```Because every version of phoenix_multi_select depends on phoenix_html ~> 3.0 and your app depends on phoenix_html ~> 4.1, no version of phoenix_multi_select is allowed.```

Adding this to mix: `{:phoenix_multi_select, git: "https://github.com/saleyn/phx-multi-select.git"},` does work.

**Comment by saleyn** [comment]
Hex updated with version 0.1.2
