### ISSUE TITLE
Style customizations for individual multi_selects when more multiple multi_select components are used.

### ISSUE THREAD

**Issue by igsp7** [saleyn/phx-multi-select#6]
Hello @saleyn!! Great job with the multi-select component. I really appreciate that you put an example project, it really saved my day!

I am using multiple multi-select components in one view and I'm trying to have different styling applied on them but I haven't found a way to do so. Am I missing something or this functionality doesn't exist? 

If the option to style the multi-select component based on an id doesn't exist, it would be a great additional!

Thanks for your great work!

**Comment by saleyn** [comment]
It should be pretty easy to extend to make it `id` specific (i.e. the customized callback would be `apply_css(id, tag, default)`).  I'll see if I can do this this week.

**Comment by saleyn** [comment]
@igsp7, please pull the latest commit and check out if it solves your problem.
