### ISSUE TITLE
Doc 

### ISSUE THREAD

**Issue by developertrinidad08** [saleyn/phx-multi-select#7]
Hello, I would be interested to know if there is more documentation apart from the one in hex ?

**Comment by saleyn** [comment]
You can check out the provided example in the `example` folder. Apart from that there's no more additional docs.

**Comment by developertrinidad08** [comment]
I am trying to use the multi_select in a live_component but when selecting options the checks are marked, but the selected topics are not shown to me I think... Has something similar ever happened to you?
![Sin título](https://github.com/saleyn/phx-multi-select/assets/112057679/78debd8e-820e-4722-ad27-95d65aa38f2a)

**Comment by saleyn** [comment]
No, I haven't encountered this behavior.  If you can come up with a small example that can reproduce it it would be helpful.
