### ISSUE TITLE
How to use on_change callback in a LiveComponent

### ISSUE THREAD

**Issue by norpan** [saleyn/phx-multi-select#9]
Hi, I'm trying to use the multi_select component inside a LiveComponent, which means that I specify phx-target={`@myself`} on regular components to have events being send to my LiveComponent instead of the parent LiveView.

However, the on_change callback of the multi_select runs code directly (via the event inside the multi_select) so I don't know how to have it send things to my LiveComponent (send() will send it to the LiveView handle_info() callback).

I'd much prefer to instead of specifying an on_change callback, I could specify a phx-change and phx-target as I do with other components.

Am I missing something? Is there a way to send the on_change options as an event to my LiveComponent instead of having it as a callback?

**Comment by saleyn** [comment]
As far as I understand in Phoenix function components do not handle events. `multi_select` is a function component.

**Comment by norpan** [comment]
Not sure what you mean. It's a liveview component but my point is that I want to handle change as an event in my own livecomponent that uses the multi select.

**Comment by saleyn** [comment]
`MultiSelect` implements a live_component, however, the function `MultiSelect.multi_select/1` is a function component, which has the limitations described above.  I need to think if it's possible to overcome this limitation.

**Comment by norpan** [comment]
Ok, it seems I can't use this component then. I made my own version in which i pass an event name and a target and then for the option select/deselect `phx-click` I do `JS.push(@event_name, value: %{select: option.id}, target: @target)` which works well for me.

Perhaps this can help somebody else having the same issue.
